### ISSUE TITLE
Uploaded pictures cause Croppie to crash Safari running on iPhone 7 Plus

### ISSUE THREAD

**Issue by edagenais** [Foliotek/Croppie#243]
Not sure what's happening, but when loading a custom image into a croppie, Safari crashes on an iPhone 7 Plus.

![crash](https://cloud.githubusercontent.com/assets/20440312/20124372/ec2e9280-a5f3-11e6-81a4-c23ae15ca1df.png)

You can easily reproduce this with the "Upload" demo on main site.

I used to run into this issue steadily on the iPhone 6/6 Plus and I equated it to a memory issue. I resolved it by minimizing the dimensions of the images selected before binding them to a croppie. That doesn't seem to be working on the iPhone 7 :-(.

Device specs:
* iPhone 7 Plus
* iOS 10.0.2
* Model FW: 1.00.03
* Browser: Safari

Has anybody else experienced this behaviour? I've seen this happen on two different devices with the same specs as above.

**Comment by sonnybaker** [comment]
Hey @edagenais, it's to do with POST sizes on iOS. Check my comment here for a workaround: https://github.com/Foliotek/Croppie/issues/185#issuecomment-238831999

**Comment by edagenais** [comment]
@sonnybaker, so did the use of a blob rather than a base64 string fix the crash issue or are you still submitting to the server first? As you stated in your comment on the other thread, it's not ideal to have to make an additional AJAX call to pre-process the image.

**Comment by robinhuse** [comment]
Having the same issue on iPhone 7 Plus. Interestingly not a problem on 6S!

**Comment by thedustinsmith** [comment]
It shouldn't be a POST issue.  The demo site isn't posting anything anywhere.  I don't have an iPhone so I can't test this, but can someone comment out lines 145-149 in demo.js (https://github.com/Foliotek/Croppie/blob/master/demo/demo.js#L145) and see if it's the binding of croppie that causes the error, or just a file reader error?

**Comment by edagenais** [comment]
@thedustinsmith, the binding and then any page scrolling or screen orientation change thereafter has been my problem from the get go - no issues with posting. By commenting out the binding I am not able to reproduce the issue.

So what "crazy" shenanigans is the binding doing outside of taking an image and drawing it to the canvas?

**Comment by thedustinsmith** [comment]
Ha ... I can't even offer up a guess at what could be causing this.  

My suggestion would be to start limiting the functionality to see at what part it breaks. 

* Is exif enabled?  Try disabling it?
* log inside this function to see if the promise is being fufilled? (https://github.com/Foliotek/Croppie/blob/master/croppie.js#L1072)
* Basically log/alert until you find the point that breaks.  Then this might be easier to track down.

Thanks for helping out.

**Comment by edagenais** [comment]
That's the thing though, it all works. The croppie gets the image displayed generally without any issue, BUUUUUT as soon as you do anything to the page (something as simple as scrolling) **CRASH!!!**. So it's something post binding. I'm pretty sure @sonnybaker is on to something about low memory issues. Somehow the croppie is taxing the memory so much that Safari has a pity-party and crashes the page.

I'm not having much luck finding evidence to support my on the browser crash logs (as always, Apple works hard to hide its logs :)).

The weird thing is, I don't get the same crashing on a similar library like Cropper for example. I would imagine the process is the same - get an image source, paint it to canvas.

**Comment by thedustinsmith** [comment]
Oh I see.  That's interesting too.  Can you try disabling mouseWheelScrolling (https://github.com/Foliotek/Croppie/blob/master/croppie.js#L479) and see if that changes anything?

Or I wonder if these might be causing some pain: 
https://github.com/Foliotek/Croppie/blob/master/croppie.js#L701

**Comment by edagenais** [comment]
So I removed both those blocks of code and it's... better, but still crashes eventually. Were you thinking there's an event bubbling leak or something of the sort?

**Comment by edagenais** [comment]
Another interesting observation - and perhaps a degree of proof to a memory issue - if I scroll the page while keeping the "upload demo" croppie within the viewport (basically scrolling up and down over and over), I can't get it to crash. However, if I scroll the croppie out of the viewport, even just 10px, and scroll back, that's when the crash happens. I can always make it crash, without fail, on an orientation change.

Is it something to do with the redraw of the canvas?

I'll keep poking around a bit.

**Comment by edagenais** [comment]
So I upgraded to 10.1 and the issue doesn't occur anymore, whether it be via a scroll or an orientation change. There was obviously some Safari changes which possibly addressed the alleged memory issues causing the crash. Although the root cause of the crash on iOS 10.0.x was never found, I'm not too concerned about it given that the latest version of the OS (at the time of writing this comment) seems to have been addressed.

Thanks @thedustinsmith for your input. This plugin is awesome.

**Comment by mPemba** [comment]
I know this has been closed, but I'm still having this issue where it crashes the browser if the file size is too big.. I'm using an iPhone 6s with the latest version of the os ( 10.2.1 ) Testing in Safari, Chrome and Firefox. 

If the image is larger than 1.25 MB then it crashes the browser with that same error ( A problem occurred with this webpage so it was reloaded. )

Has this been solved in any of the other issue chains? I'm looking at #186, #185, #178, and this one and cannot seem to find the right answer. 

If I take a picture using the front facing/ selfie camera the file size is usually under 1 MB and I can crop/ rotate/ adjust and upload the image. If I take a picture using the outward facing camera it's usually a larger file size and either crashes the browser immediately, or when I try and adjust the placement or rotate the photo it will crash.

**Comment by benhath** [comment]
Problem still exists. Any solutions?

**Comment by zspitzer** [comment]
FYI: I have filed a bug against webkit for this problem https://bugs.webkit.org/show_bug.cgi?id=172533

**Comment by macsj200** [comment]
I too still have this issue.

**Comment by dev14synova** [comment]
Hi Guys,
I have fixed this issue. This issue occurs because size of image upload is so large ( iphone7 > 4000px). So we need reduce size before use Croppie.

1. Creat div contain image and canvas to reduce size. Draw the image by canvas after upload => fit size image = size canvas ( I set max 1024 )
2. Export new url from canvas with new size ( max 1024 ).
3. Use croppie with new url.

**Comment by 5Sense-PhuocLoiTran** [comment]
Problem still exists. I have crashed safari app on Iphone 11-12-13promax. Any solutions? Tks you
