### ISSUE TITLE
Cropping when rotating

### ISSUE THREAD

**Issue by chilipote** [Foliotek/Croppie#293]
Hi, 

I would like to know, if it's a bug or something I did wrong : I added today the `enableOrientation: true` option. Working great, the image is rotating. Yay. But I have some troubles during cropping.

In some words : I'm having an image larger than higher. When I flip it to the right, the image become higher than larger. If I try to crop the bottom of the image, the result can be transparent. And because images are always better than words :

Here the image I want to upload :
![croppie_1](https://cloud.githubusercontent.com/assets/3026891/23867553/a1d548d0-07f2-11e7-9dda-05cfb4fcdddb.png)

Then I flip it 
![croppie_2](https://cloud.githubusercontent.com/assets/3026891/23867563/ad792ea4-07f2-11e7-8d91-657e4405707e.png)

I select the bottom of the image
![croppie_3](https://cloud.githubusercontent.com/assets/3026891/23867564/ad79ea56-07f2-11e7-8054-b8f5bb44a313.png)

And here the result
![croppie_4](https://cloud.githubusercontent.com/assets/3026891/23867590/c03e583e-07f2-11e7-87a5-1a28f37ca4d9.png)

Am I the only one who experienced that ? Let me know if it's not clear. 

Last version of Croppie : 2.4.1
Google chrome
Original dimension of the image : 1000 * 667
Viewport : 200 * 200
Boundary : 260 * 260

**Comment by chilipote** [comment]
I think, maybe I found the problem : 

croppie.js, `_getCanvas`, line 993. 

``` javascript
    if (right > self._originalImageWidth) {
      width = self._originalImageWidth - left;
      outWidth = width;
    }
    if (bottom > self._originalImageHeight) {
      height = self._originalImageHeight - top;
      outHeight = height;
    }
```

I think this check, `right > self._originalImageWidth` is wrong in rotate situation, what do you think ?

**Comment by INJumbo** [comment]
I am having this issue too, commented those if statements and issue has gone :) 
Thanks !

**Comment by INJumbo** [comment]
In my case those lines was like this 
 
 if ((left + width) > self._originalImageWidth) {
            width = self._originalImageWidth - left;
            outWidth = width;
        }
        if ((top + height) > self._originalImageHeight) {
            height = self._originalImageHeight - top;
            outHeight = height;
        }

**Comment by chilipote** [comment]
Which version did you have ?

**Comment by raykudo** [comment]
+1

**Comment by jlozanoher** [comment]
Same issue for me, when rotating and moving vertically.

**Comment by thedustinsmith** [comment]
#326 was believed to has resolved this issue, but it seems some people are still having it.  I can't get it to happen myself.

I've used the rotation example on demo page, rotated, dragged to the bottom, and the resulting image seems to be correct.  I've not made a release since 326 was merged in, so I'm just using the code in master to do so.  Can anyone pull the latest code from master and confirm that this issue is a thing of the past?

**Comment by antoinelorcy** [comment]
I think this is fixed. I don't reproduce anymore using the latest 2.5.0

**Comment by JonathonRichardson** [comment]
I can still reproduce this with both `master` and the `2.5.0`.  It only happens with `enforceBoundary`  disabled an image with an aspect ratio of something other than `1:1`.  It looks to me like the problem is that the original image's width and height are used during the final drawing calculation.  If the image was rotated an odd multiple of 90 degrees, that means it is using the width as the height an vice versa.  I'm able to fix this so far (I haven't tested it extensively yet) by adding the following to the end of the `_rotate()` function to swap the original values: 

```
if ((deg % 180) !== 0) {
    var lastOriginalHeight = this._originalImageHeight;
    this._originalImageHeight = this._originalImageWidth;
    this._originalImageWidth = lastOriginalHeight;
}
```

@thedustinsmith, does that seem like the right way to fix this?

**Comment by Hesesses** [comment]
having the same problem as above

**Comment by rickthewebdev** [comment]
@JonathonRichardson solucion fixed it for me. Thank you :+1:

**Comment by hikari82** [comment]
Thanks to @JonathonRichardson.. it fixed for me to.

**Comment by thedustinsmith** [comment]
Thanks for all the feedback in this one guys.  I believe this issue is fixed in 2.5.2.  I can't recreate the issue using the rotate example in the demo page.  2.5.2 should be released soon.

**Comment by bhavikvaishnani** [comment]
I have downloaded 2.5.2, And for the normal size image, it is working fine. So thanks once again for the wonderful plugin, But when I try with an image of 1203 x 3869. I can still reproduce it. (resultant image not as expected)

**Comment by thedustinsmith** [comment]
@bhavikvaishnani Can you provide a video demonstrating the issues, or steps to recreate the issue?

**Comment by wimZ** [comment]
I had a similar issue when rotating a portrait shaped image 90 degress, the result is limited to original width. 
I do not want to switch off enforceBoundaries. 

I added the below code in function _rotate @ line 1425
It may not be the most optimum code, but it gives me a correct result (so far). 

`if (deg === 90 || deg === 270 || deg === -90 || deg === -270) {
           var temp = self._originalImageWidth;
           self._originalImageWidth = self._originalImageHeight;
           self._originalImageHeight = temp;
        }
`
Have not encountered any side effects yet.

**Comment by mishavee** [comment]
For me the problem showed in Croppie v2.4.1.  Playing with jsbin, v2.4.0 has the problem, earlier versions don't work with my example, and the problem no longer shows from v2.5.1.

Example link:
http://jsbin.com/hulowasusi/edit

Steps:

1. Rotate right.
2. Drag dog all the way up so the eye is at the crop edge.
3. Press result.
4. Scroll down to see if the cropped image has a white area on the bottom.

**Comment by rohitPagal** [comment]
yup @mishavee the cropped dog does have a white area :( 👍     has this issue been solved ?

**Comment by pbf79** [comment]
@rohitPagal  it seems like a regression (in 2.6.4).
If i use https://raw.githubusercontent.com/Foliotek/Croppie/pre-2.5.2/croppie.min.js it works.

**Comment by mrhaver** [comment]
@mishavee thanks for your jsbin 👍 

Bug still seems to occur in 2.6.3 and 2.6.4 unfortunately just for your information. 

In 2.6.2 this bug is fixed, but i can't use this version in my code.

**Comment by mjunaid720** [comment]
it works fine on 2.4.1 at least

**Comment by vadymstebakov** [comment]
@mrhaver Have you decided this problem in 2.6.4?

**Comment by vadymstebakov** [comment]
@thedustinsmith Bug still occur in 2.6.4. When I rotate in the bottom of the image. Here is a link: https://codepen.io/by_olegovichs/pen/LYVMNaY?editors=0010

**Comment by tristanbenier** [comment]
Hi guys.
I am facing the same issue with 2.6.4.

https://github.com/Foliotek/Croppie/pull/711 fixed the issue for me.

**Comment by martinduris** [comment]
It is possible to expect fix (i have seen PR which should fix it) ? Thanks
